### ISSUE TITLE
Missing hidden_features

### ISSUE THREAD

**Issue by QianpengLi577** [Lvchangze/SpikeBERT#1]
Excellent work!
What is the `hidden_features` in the experiment?
https://github.com/Lvchangze/SpikeBERT/blob/main/model/new_spikformer.py#L118C107-L118C107

**Comment by Lvchangze** [comment]
In Spikformer (Zhou, 2023), the hidden feature is the [in_feature]. But we follow BERT to choose [4 * in_feature].
However, we found little difference in performance between these two choices. So both [in_feature] and [4 * in_feature] are Okay.
Thank you!
